// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewUser struct {
	Email string `json:"email"`
	UID   string `json:"uid"`
	Age   int    `json:"age"`
}

type UIDInput struct {
	UID string `json:"uid"`
}

type User struct {
	ID    int    `json:"id"`
	Email string `json:"email"`
	UID   string `json:"uid"`
	Age   int    `json:"age"`
}
