// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type IDInput struct {
	ID int `json:"id"`
}

type NewUser struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
	Age  int    `json:"age"`
}

type User struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
	Age  int    `json:"age"`
}
